const actions = {
  UPDATE_ADDRESS: 'UPDATE_ADDRESS',
  WALLET_DISCONNECT: 'WALLET_DISCONNECT',
  WALLET_UPDATE_STATS: 'WALLET_UPDATE_STATS',
  UPDATE_STATS: 'UPDATE_STATS',
  UPDATE_OUTSTANDING_STATS: 'UPDATE_OUTSTANDING_STATS',
  UPDATE_RISK_TREASURY_VALUE: 'UPDATE_RISK_TREASURY_VALUE',
  UPDATE_INVESTMENT_LIST: 'UPDATE_INVESTMENT_LIST',
  UPDATE_AIRDROPS: 'UPDATE_AIRDROPS',
  GET_STATS_NOT_CONNECTED: 'GET_STATS_NOT_CONNECTED',
}

export default actions;