// export const GET_FE_STATS = 'GET_FE_STATS'
// export const GET_TRANSACTION_LIST = 'GET_TRANSACTION_LIST'

// export const UPDATE_AIRDROP_AMOUNT = 'UPDATE_AIRDROP_AMOUNT'

const actions = {
  UPDATE_ADDRESS: 'UPDATE_ADDRESS',
  WALLET_DISCONNECT: 'WALLET_DISCONNECT',
  WALLET_UPDATE_STATS: 'WALLET_UPDATE_STATS',
  UPDATE_STATS: 'UPDATE_STATS',
  UPDATE_OUTSTANDING_STATS: 'UPDATE_OUTSTANDING_STATS',
}

export default actions;